export const ANALYTICS_ACTION = {
    PAGE_VIEW: 'Page view',
    PIANO_ENABLED: 'Piano enabled',
    PIANO_DISABLED: 'Piano disabled',
    RECORD_STARTED: 'Recording started',
    RECORD_STOPPED: 'Recording stopped',
    INSTRUMENT_SELECTOR_OPENED: 'Instrument selector opened',
    INSTRUMENT_CHANGED: 'Instrument changed',
    SOUND_SETTINGS_OPENED: 'Sound settings opened',
    STYLES_SETTINGS_OPENED: 'Styles settings opened',
    KEY_ASSIST_OPENED: 'Key assist opened',
    SUSTAIN_CHANGED: 'Sustain changed',
    TRANSPOSE_CHANGED: 'Transpose changed',
    VOLUME_CHANGED: 'Volume changed',
    METRONOME_TOGGLED: 'Metronome toggled',
    METRONOME_TEMPO_CHANGED: 'Metronome tempo changed',
    METRONOME_VOLUME_CHANGED: 'Metronome volume changed',
    PIANO_THEME_CHANGED: 'Piano theme changed',
    BACKGROUND_THEME_CHANGED: 'Background theme changed',
    MUSIC_SHEET_THEME_CHANGED: 'Music sheet theme changed',
    PATTERN_THEME_CHANGED: 'Pattern theme changed',
    KEYBOARD_DISPLAY_TOGGLED: 'Keyboard display toggled',
    NOTE_NAMES_TOGGLED: 'Note names toggled',
    SHEET_CHANGED: 'Sheet changed',
    SHEET_FAVORITED: 'Sheet favorited',
    SHEET_UNFAVORITED: 'Sheet unfavorited',
    CUSTOM_SHEET_ADDED: 'Custom sheet added',
    SHEET_DELETED: 'Sheet deleted',
    QUOTE_DISPLAY_TOGGLED: 'Quote display toggled',
    QUOTE_INTERVAL_CHANGED: 'Quote interval changed',
    QUOTE_FAVORITES_FILTER_TOGGLED: 'Quote favorites filter toggled',
    QUOTE_FAVORITED: 'Quote favorited',
    QUOTE_UNFAVORITED: 'Quote unfavorited',
    SHEET_PLAYBACK_STARTED: 'Sheet playback started',
    SHEET_PLAYBACK_PAUSED: 'Sheet playback paused',
    SHEET_PLAYBACK_STOPPED: 'Sheet playback stopped',
    SHEET_PAGE_CHANGED: 'Sheet page changed',
    SHEET_TEMPO_CHANGED: 'Sheet tempo changed'
}