/**
 * Harmonious theme preset combinations
 * Curated combinations of piano theme, background, and music sheet for optimal visual harmony
 */

import { QUOTE_STYLES, QuoteStyle } from '@/theme/definitions/quote-styles';
import type { HeaderTypographyStyle } from '../header/header-typography';
import { HEADER_THEME_STYLES, HeaderThemeStyle } from '@/theme/definitions/header-theme-styles';
import { PLAYBACK_BAR_STYLES, PlaybackBarStyle } from '@/theme/definitions/playback-bar-styles';

// Re-export for convenience
export type { QuoteStyle, HeaderThemeStyle, PlaybackBarStyle };

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  pianoTheme: string;
  backgroundTheme: string;
  musicSheetTheme: string;
  patternTheme?: string; // NEW: 4th independent theme component (optional, defaults to 'none')
  patternIntensity?: number; // Pattern opacity multiplier (0.5 = 50%, 1.0 = 100%, 2.0 = 200%), defaults to 1.0
  category: 'classic' | 'modern' | 'cultural' | 'nature' | 'artistic' | 'vintage' | 'professional' | 'romantic' | 'energetic' | 'minimalist' | 'luxurious' | 'sci-fi';
  headerStyle: HeaderTypographyStyle;
  headerThemeStyle: HeaderThemeStyle;
  quoteStyle: QuoteStyle;
  playbackBarStyle: PlaybackBarStyle;
}

export type ThemePresetCategory = ThemePreset['category'];

export const THEME_PRESETS: ThemePreset[] = [
  // Classic Presets
  {
    id: 'classic-elegance',
    name: 'Classic Elegance',
    description: 'Timeless wooden piano with warm vintage tones',
    pianoTheme: 'wooden',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-1',
    patternTheme: 'classic-wood',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  {
    id: 'vintage-scholar',
    name: 'Vintage Scholar',
    description: 'Traditional study atmosphere with aged paper',
    pianoTheme: 'wooden',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-3',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  {
    id: 'mahogany-warmth',
    name: 'Mahogany Warmth',
    description: 'Rich mahogany with classic parchment',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-4',
    patternTheme: 'dark-mahogany',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  {
    id: 'dark-symphony',
    name: 'Dark Symphony',
    description: 'Dramatic black piano in dark ambiance',
    pianoTheme: 'black',
    backgroundTheme: 'dark',
    musicSheetTheme: 'paper-3',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  
  // Modern Presets
  {
    id: 'modern-minimalist',
    name: 'Modern Minimalist',
    description: 'Clean white piano with contemporary paper',
    pianoTheme: 'white',
    backgroundTheme: 'white',
    musicSheetTheme: 'paper-2',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  {
    id: 'nordic-serenity',
    name: 'Nordic Serenity',
    description: 'Cool Nordic ice with morning sky gradient',
    pianoTheme: 'nordicIce',
    backgroundTheme: 'morning-sky',
    musicSheetTheme: 'paper-6',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  {
    id: 'metal-cool',
    name: 'Metal Cool',
    description: 'Industrial metal with cool marble finish',
    pianoTheme: 'metal',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-12',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  {
    id: 'rose-romance',
    name: 'Rose Romance',
    description: 'Elegant rose gold with soft cream tones',
    pianoTheme: 'roseGold',
    backgroundTheme: 'zen-sakura-dawn',
    musicSheetTheme: 'paper-5',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  
  // Cultural Presets
  {
    id: 'japanese-zen',
    name: 'Japanese Zen',
    description: 'Tranquil bamboo garden with watercolor aesthetic',
    pianoTheme: 'wooden',
    backgroundTheme: 'zen-bamboo-stone',
    musicSheetTheme: 'paper-8',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'chinese-imperial',
    name: 'Chinese Imperial',
    description: 'Palace vermillion gold with ancient scroll',
    pianoTheme: 'mahogany',
    backgroundTheme: 'gufeng-vermillion-gold',
    musicSheetTheme: 'paper-10',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'ink-jade',
    name: 'Ink & Jade',
    description: 'Traditional Chinese ink painting with kraft paper',
    pianoTheme: 'black',
    backgroundTheme: 'gufeng-ink-jade',
    musicSheetTheme: 'paper-11',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'hindu-sacred',
    name: 'Hindu Sacred',
    description: 'Saffron and marigold with delicate vellum',
    pianoTheme: 'roseGold',
    backgroundTheme: 'leela-saffron-marigold',
    musicSheetTheme: 'paper-13',
    patternTheme: 'saffron-marigold',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'peacock-divine',
    name: 'Peacock Divine',
    description: 'Krishna\'s celestial hues with modern elegance',
    pianoTheme: 'metal',
    backgroundTheme: 'leela-peacock-divine',
    musicSheetTheme: 'paper-2',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'earth-mystic',
    name: 'Earth Mystic',
    description: 'Spiritual earthy path with weathered paper',
    pianoTheme: 'mahogany',
    backgroundTheme: 'isha-earth-mystic',
    musicSheetTheme: 'paper-3',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'divine-glory',
    name: 'Divine Glory',
    description: 'Sacred radiance with leather-bound elegance',
    pianoTheme: 'white',
    backgroundTheme: 'sacred-light-glory',
    musicSheetTheme: 'paper-14',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'islamic-elegance',
    name: 'Islamic Elegance',
    description: 'Emerald and gold with marble sophistication',
    pianoTheme: 'metal',
    backgroundTheme: 'islamic-emerald-gold',
    musicSheetTheme: 'paper-12',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'tibetan-enlightenment',
    name: 'Tibetan Enlightenment',
    description: 'Sacred mountains with prayer wheel sanctuary',
    pianoTheme: 'tibetanWood',
    backgroundTheme: 'tibet-sacred-mountains',
    musicSheetTheme: 'paper-10',
    patternTheme: 'tibetan-sacred',
    category: 'cultural',
    headerStyle: 'tibetan-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'rumi-mystic-dance',
    name: 'Rumi\'s Mystic Dance',
    description: 'Sufi poetry and whirling dervish spirituality',
    pianoTheme: 'mahogany',
    backgroundTheme: 'sufi-whirling-mystic',
    musicSheetTheme: 'paper-10',
    category: 'cultural',
    headerStyle: 'persian-poetic',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'kabbalah-wisdom',
    name: 'Kabbalah Wisdom',
    description: 'Jewish mysticism and Tree of Life sefirot',
    pianoTheme: 'black',
    backgroundTheme: 'kabbalah-tree-of-life',
    musicSheetTheme: 'paper-13',
    category: 'cultural',
    headerStyle: 'hebrew-mystical',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'shinto-sanctuary',
    name: 'Shinto Sanctuary',
    description: 'Sacred torii gates and kami nature spirits',
    pianoTheme: 'white',
    backgroundTheme: 'shinto-torii-dawn',
    musicSheetTheme: 'paper-8',
    category: 'cultural',
    headerStyle: 'shinto-sacred',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'native-great-spirit',
    name: 'Great Spirit',
    description: 'Native American earth wisdom and spirit sky',
    pianoTheme: 'wooden',
    backgroundTheme: 'native-spirit-sky',
    musicSheetTheme: 'paper-7',
    category: 'cultural',
    headerStyle: 'native-spirit',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'celtic-druid-grove',
    name: 'Druid Grove',
    description: 'Celtic forest magic and ancient oak wisdom',
    pianoTheme: 'wooden',
    backgroundTheme: 'celtic-forest-mist',
    musicSheetTheme: 'paper-11',
    category: 'cultural',
    headerStyle: 'celtic-ancient',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'sikh-divine-light',
    name: 'Divine Light',
    description: 'Sikh spiritual sovereignty and Guru\'s wisdom',
    pianoTheme: 'roseGold',
    backgroundTheme: 'sikh-khanda-divine',
    musicSheetTheme: 'paper-5',
    category: 'cultural',
    headerStyle: 'sikh-gurmukhi',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'theravada-buddhism',
    name: 'Theravada Buddhism',
    description: 'The path of the elders, with saffron robes and serene mindfulness.',
    pianoTheme: 'wooden',
    backgroundTheme: 'leela-saffron-marigold',
    musicSheetTheme: 'paper-13',
    patternTheme: 'saffron-marigold',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'mahayana-buddhism',
    name: 'Mahayana Buddhism',
    description: 'The great vehicle, embodying universal compassion and the Bodhisattva path.',
    pianoTheme: 'mahogany',
    backgroundTheme: 'bodhisattva-gardens',
    musicSheetTheme: 'paper-8',
    patternTheme: 'lotus-scroll',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'vajrayana-buddhism',
    name: 'Vajrayana Buddhism',
    description: 'The diamond vehicle, symbolizing indestructible clarity and potent methods.',
    pianoTheme: 'tibetanWood',
    backgroundTheme: 'vajrayana-sky-temple',
    musicSheetTheme: 'paper-14',
    patternTheme: 'vajrayana-diamond',
    category: 'cultural',
    headerStyle: 'tibetan-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'zen-buddhism',
    name: 'Zen Buddhism',
    description: 'Embracing simplicity and mindfulness with natural textures.',
    pianoTheme: 'wooden',
    backgroundTheme: 'zen-bamboo-stone',
    musicSheetTheme: 'paper-7',
    patternTheme: 'tatami-mat',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  
  // Nature Presets
  {
    id: 'forest-peace',
    name: 'Forest Peace',
    description: 'Natural forest with eco-friendly recycled paper',
    pianoTheme: 'wooden',
    backgroundTheme: 'gradient-forest',
    musicSheetTheme: 'paper-7',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep ocean gradient with notebook simplicity',
    pianoTheme: 'black',
    backgroundTheme: 'gradient-ocean',
    musicSheetTheme: 'paper-9',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  
  // Artistic Presets
  {
    id: 'sunset-dreams',
    name: 'Sunset Dreams',
    description: 'Warm sunset with artistic canvas texture',
    pianoTheme: 'roseGold',
    backgroundTheme: 'gradient-sunset',
    musicSheetTheme: 'paper-15',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
  {
    id: 'morning-light',
    name: 'Morning Light',
    description: 'Peaceful morning with textured linen',
    pianoTheme: 'white',
    backgroundTheme: 'morning-sky',
    musicSheetTheme: 'paper-6',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
  {
    id: 'cosmic-serenade',
    name: 'Cosmic Serenade',
    description: 'A journey through deep space with celestial starlight.',
    pianoTheme: 'metal',
    backgroundTheme: 'cosmic-deep-space',
    musicSheetTheme: 'paper-12',
    patternTheme: 'cosmic-galaxy',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
  
  // Vintage Presets
  {
    id: 'vintage-parlor',
    name: 'Vintage Parlor',
    description: 'Classic parlor piano with aged scroll',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-10',
    category: 'vintage',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.vintage,
    quoteStyle: QUOTE_STYLES.vintage,
    playbackBarStyle: PLAYBACK_BAR_STYLES.vintage,
  },
  {
    id: 'vintage-library',
    name: 'Vintage Library',
    description: 'Scholarly atmosphere with leather-bound notes',
    pianoTheme: 'wooden',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-14',
    category: 'vintage',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.vintage,
    quoteStyle: QUOTE_STYLES.vintage,
    playbackBarStyle: PLAYBACK_BAR_STYLES.vintage,
  },
  {
    id: 'vintage-attic',
    name: 'Vintage Attic',
    description: 'Dusty attic piano with kraft paper',
    pianoTheme: 'wooden',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-11',
    category: 'vintage',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.vintage,
    quoteStyle: QUOTE_STYLES.vintage,
    playbackBarStyle: PLAYBACK_BAR_STYLES.vintage,
  },
  {
    id: 'vintage-salon',
    name: 'Vintage Salon',
    description: 'European salon with parchment elegance',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-4',
    category: 'vintage',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.vintage,
    quoteStyle: QUOTE_STYLES.vintage,
    playbackBarStyle: PLAYBACK_BAR_STYLES.vintage,
  },
  {
    id: 'vintage-conservatory',
    name: 'Vintage Conservatory',
    description: 'Music conservatory with classic vellum',
    pianoTheme: 'black',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-13',
    category: 'vintage',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.vintage,
    quoteStyle: QUOTE_STYLES.vintage,
    playbackBarStyle: PLAYBACK_BAR_STYLES.vintage,
  },
  
  // Professional Presets
  {
    id: 'concert-hall',
    name: 'Concert Hall',
    description: 'Grand concert hall with pristine modern paper',
    pianoTheme: 'black',
    backgroundTheme: 'white',
    musicSheetTheme: 'paper-2',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  {
    id: 'recording-studio',
    name: 'Recording Studio',
    description: 'Professional studio with clean white setup',
    pianoTheme: 'black',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-2',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  {
    id: 'music-school',
    name: 'Music School',
    description: 'Educational environment with notebook paper',
    pianoTheme: 'white',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-9',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  {
    id: 'office-piano',
    name: 'Office Piano',
    description: 'Corporate elegance with marble sophistication',
    pianoTheme: 'metal',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-12',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  {
    id: 'theater-stage',
    name: 'Theater Stage',
    description: 'Theatrical black with dramatic aged paper',
    pianoTheme: 'black',
    backgroundTheme: 'dark',
    musicSheetTheme: 'paper-3',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  {
    id: 'jazz-club',
    name: 'Jazz Club',
    description: 'Moody jazz atmosphere with kraft paper',
    pianoTheme: 'black',
    backgroundTheme: 'dark',
    musicSheetTheme: 'paper-11',
    category: 'professional',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.professional,
    quoteStyle: QUOTE_STYLES.professional,
    playbackBarStyle: PLAYBACK_BAR_STYLES.professional,
  },
  
  // Romantic Presets
  {
    id: 'romantic-serenade',
    name: 'Romantic Serenade',
    description: 'Rose gold elegance with cream romance',
    pianoTheme: 'roseGold',
    backgroundTheme: 'gradient-sunset',
    musicSheetTheme: 'paper-5',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  {
    id: 'moonlight-sonata',
    name: 'Moonlight Sonata',
    description: 'Ethereal white with soft linen',
    pianoTheme: 'white',
    backgroundTheme: 'morning-sky',
    musicSheetTheme: 'paper-6',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  {
    id: 'love-letters',
    name: 'Love Letters',
    description: 'Intimate rose gold with delicate vellum',
    pianoTheme: 'roseGold',
    backgroundTheme: 'zen-sakura-dawn',
    musicSheetTheme: 'paper-13',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  {
    id: 'sunset-piano',
    name: 'Sunset Piano',
    description: 'Golden hour warmth with vintage paper',
    pianoTheme: 'wooden',
    backgroundTheme: 'gradient-sunset',
    musicSheetTheme: 'paper-1',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    description: 'Sakura dreams with watercolor artistry',
    pianoTheme: 'white',
    backgroundTheme: 'zen-sakura-dawn',
    musicSheetTheme: 'paper-8',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  {
    id: 'candlelight',
    name: 'Candlelight',
    description: 'Warm candlelit evening with aged charm',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-3',
    category: 'romantic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.romantic,
    quoteStyle: QUOTE_STYLES.romantic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.romantic,
  },
  
  // Energetic Presets
  {
    id: 'electric-burst',
    name: 'Electric Burst',
    description: 'Vibrant metal with notebook energy',
    pianoTheme: 'metal',
    backgroundTheme: 'gradient-forest',
    musicSheetTheme: 'paper-9',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  {
    id: 'tropical-vibes',
    name: 'Tropical Vibes',
    description: 'Bright white with forest freshness',
    pianoTheme: 'white',
    backgroundTheme: 'gradient-forest',
    musicSheetTheme: 'paper-7',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  {
    id: 'sunrise-energy',
    name: 'Sunrise Energy',
    description: 'Morning burst with canvas creativity',
    pianoTheme: 'roseGold',
    backgroundTheme: 'morning-sky',
    musicSheetTheme: 'paper-15',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    description: 'Dynamic ocean with watercolor flow',
    pianoTheme: 'white',
    backgroundTheme: 'gradient-ocean',
    musicSheetTheme: 'paper-8',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  {
    id: 'festival-lights',
    name: 'Festival Lights',
    description: 'Celebratory colors with modern sheets',
    pianoTheme: 'metal',
    backgroundTheme: 'gradient-sunset',
    musicSheetTheme: 'paper-2',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  {
    id: 'spring-bloom',
    name: 'Spring Bloom',
    description: 'Fresh spring with recycled eco paper',
    pianoTheme: 'white',
    backgroundTheme: 'gradient-forest',
    musicSheetTheme: 'paper-7',
    category: 'energetic',
    headerStyle: 'energetic-bold',
    headerThemeStyle: HEADER_THEME_STYLES.energetic,
    quoteStyle: QUOTE_STYLES.energetic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.energetic,
  },
  
  // Minimalist Presets
  {
    id: 'pure-white',
    name: 'Pure White',
    description: 'Ultimate minimalism with modern clarity',
    pianoTheme: 'white',
    backgroundTheme: 'white',
    musicSheetTheme: 'paper-2',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    description: 'Fresh start with light gray simplicity',
    pianoTheme: 'white',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-2',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'zen-minimal',
    name: 'Zen Minimal',
    description: 'Peaceful simplicity with linen texture',
    pianoTheme: 'white',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-6',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'arctic-minimal',
    name: 'Arctic Minimal',
    description: 'Nordic ice with pristine morning sky',
    pianoTheme: 'nordicIce',
    backgroundTheme: 'white',
    musicSheetTheme: 'paper-2',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Black and white with marble elegance',
    pianoTheme: 'black',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-12',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'simple-beauty',
    name: 'Simple Beauty',
    description: 'Understated white with cream warmth',
    pianoTheme: 'white',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-5',
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    description: 'Carefully calibrated light theme using mathematically precise color ratios for optimal readability and reduced eye strain',
    pianoTheme: 'solarized',
    backgroundTheme: 'solarized-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'solarized-light',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    description: 'Precisely balanced dark theme with carefully calibrated colors designed for prolonged coding sessions',
    pianoTheme: 'solarized',
    backgroundTheme: 'solarized-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'solarized-dark',
    patternIntensity: 0.2,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'monokai-light',
    name: 'Monokai Light',
    description: 'Bright Monokai-inspired theme with vibrant syntax highlighting colors for enhanced readability',
    pianoTheme: 'monokai',
    backgroundTheme: 'monokai-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'monokai-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'monokai-dark',
    name: 'Monokai Dark',
    description: 'Classic Monokai dark theme with vibrant syntax colors designed for prolonged coding sessions',
    pianoTheme: 'monokai',
    backgroundTheme: 'monokai-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'monokai-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'dracula-dark',
    name: 'Dracula Dark',
    description: 'Classic Dracula dark theme with high contrast and vibrant syntax highlighting colors',
    pianoTheme: 'dracula',
    backgroundTheme: 'dracula-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'dracula-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    description: 'GitHub\'s official light theme with clean design and professional blue accents for optimal readability',
    pianoTheme: 'github-light',
    backgroundTheme: 'github-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'github-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: 'GitHub\'s official dark theme with professional blue accents and clean design for extended coding sessions',
    pianoTheme: 'github-dark',
    backgroundTheme: 'github-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'github-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    description: 'Popular dark theme with Material Design influence and carefully balanced colors for optimal readability',
    pianoTheme: 'oneDarkPro',
    backgroundTheme: 'one-dark-pro',
    musicSheetTheme: 'paper-3',
    patternTheme: 'one-dark-pro',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'ayu-light',
    name: 'Ayu Light',
    description: 'Clean light theme with soft colors and pleasant text readability for comfortable coding',
    pianoTheme: 'ayuLight',
    backgroundTheme: 'ayu-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'ayu-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'ayu-mirage',
    name: 'Ayu Mirage',
    description: 'Balanced theme between light and dark with soft colors and high contrast elements',
    pianoTheme: 'ayuMirage',
    backgroundTheme: 'ayu-mirage',
    musicSheetTheme: 'paper-3',
    patternTheme: 'ayu-mirage',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    description: 'Modern dark theme with high contrast and vibrant accents for extended coding sessions',
    pianoTheme: 'ayuDark',
    backgroundTheme: 'ayu-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'ayu-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Dark blue theme perfect for late-night coding with high contrast text and professional appearance',
    pianoTheme: 'nightOwl',
    backgroundTheme: 'night-owl',
    musicSheetTheme: 'paper-3',
    patternTheme: 'night-owl',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'Cyberpunk-inspired theme with neon accents and glowing lights for a futuristic aesthetic',
    pianoTheme: 'tokyoNight',
    backgroundTheme: 'tokyo-night',
    musicSheetTheme: 'paper-3',
    patternTheme: 'tokyo-night',
    patternIntensity: 0.35,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'shades-of-purple',
    name: 'Shades of Purple',
    description: 'Bold purple color scheme with elegant, sophisticated look and vibrant accents',
    pianoTheme: 'shadesOfPurple',
    backgroundTheme: 'shades-of-purple',
    musicSheetTheme: 'paper-3',
    patternTheme: 'shades-of-purple',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    description: 'High contrast theme with almost fluorescent colors and retro aesthetic',
    pianoTheme: 'cobalt2',
    backgroundTheme: 'cobalt2',
    musicSheetTheme: 'paper-3',
    patternTheme: 'shades-of-purple', // Reusing purple pattern for cobalt2
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'winter-is-coming',
    name: 'Winter is Coming',
    description: 'Cool blue theme inspired by Game of Thrones with icy, northern aesthetics',
    pianoTheme: 'winterIsComing',
    backgroundTheme: 'winter-is-coming',
    musicSheetTheme: 'paper-3',
    patternTheme: 'tokyo-night', // Reusing tokyo night pattern for winter theme
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'noctis',
    name: 'Noctis',
    description: 'Green-based theme with modern design and multiple variants for a fresh look',
    pianoTheme: 'noctis',
    backgroundTheme: 'noctis',
    musicSheetTheme: 'paper-3',
    patternTheme: 'ayu-dark', // Reusing ayu dark pattern for noctis
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'material',
    name: 'Material Theme',
    description: 'Google\'s Material Design colors with modern dark aesthetics and refined typography',
    pianoTheme: 'material',
    backgroundTheme: 'material',
    musicSheetTheme: 'paper-3',
    patternTheme: 'material',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'community-material',
    name: 'Community Material',
    description: 'Enhanced Material theme with more refined color variants and professional styling',
    pianoTheme: 'communityMaterial',
    backgroundTheme: 'community-material',
    musicSheetTheme: 'paper-3',
    patternTheme: 'community-material',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'bluloco-dark',
    name: 'Bluloco Dark',
    description: 'Sophisticated designer color scheme with enhanced syntax highlighting and refined aesthetics',
    pianoTheme: 'blulocoDark',
    backgroundTheme: 'bluloco-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'bluloco-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'bluloco-light',
    name: 'Bluloco Light',
    description: 'Clean and sophisticated light designer color scheme with balanced contrast',
    pianoTheme: 'blulocoLight',
    backgroundTheme: 'bluloco-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'bluloco-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'rouge',
    name: 'Rouge',
    description: 'Material-inspired theme with flushed color palette and elegant dark styling',
    pianoTheme: 'rouge',
    backgroundTheme: 'rouge',
    musicSheetTheme: 'paper-3',
    patternTheme: 'rouge',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'sublime-material',
    name: 'Sublime Material',
    description: 'Material theme inspired by Sublime Text with distinctive red-pink accents',
    pianoTheme: 'sublimeMaterial',
    backgroundTheme: 'sublime-material',
    musicSheetTheme: 'paper-3',
    patternTheme: 'sublime-material',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Soft, cold Nordic-inspired colors with arctic blue and green accents for serene coding',
    pianoTheme: 'nord',
    backgroundTheme: 'nord',
    musicSheetTheme: 'paper-3',
    patternTheme: 'nord',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'atom-one-dark',
    name: 'Atom One Dark',
    description: 'Clean theme from the Atom editor with balanced grays and professional blue accents',
    pianoTheme: 'atomOneDark',
    backgroundTheme: 'atom-one-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'atom-one-dark',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'synthwave84',
    name: 'SynthWave \'84',
    description: 'Retro 80s neon theme with vibrant pinks, purples, and cyberpunk aesthetics for futuristic piano playing',
    pianoTheme: 'synthwave84',
    backgroundTheme: 'synthwave84',
    musicSheetTheme: 'paper-3',
    patternTheme: 'synthwave84',
    patternIntensity: 0.35,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'panda',
    name: 'Panda',
    description: 'Japanese-inspired theme with pandas and vibrant colors featuring pinks and cyans for a playful experience',
    pianoTheme: 'panda',
    backgroundTheme: 'panda',
    musicSheetTheme: 'paper-3',
    patternTheme: 'panda',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'hop-light',
    name: 'Hop Light',
    description: 'Bright and refreshing light theme with vibrant orange, green, and pink accents for cheerful piano sessions',
    pianoTheme: 'hopLight',
    backgroundTheme: 'hop-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'hop-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'snazzy-light',
    name: 'Snazzy Light',
    description: 'Vibrant modern light theme with orange, teal, and blue accents for a colorful and energetic feel',
    pianoTheme: 'snazzyLight',
    backgroundTheme: 'snazzy-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'snazzy-light',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'one-monokai',
    name: 'One Monokai',
    description: 'Colorful Monokai variant with vibrant red, green, and blue accents for a lively coding-inspired theme',
    pianoTheme: 'oneMonokai',
    backgroundTheme: 'one-monokai',
    musicSheetTheme: 'paper-3',
    patternTheme: 'one-monokai',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'poimandres',
    name: 'Poimandres',
    description: 'Minimal dark theme with semantic coloring and teal blue accents for focused and elegant piano playing',
    pianoTheme: 'poimandres',
    backgroundTheme: 'poimandres',
    musicSheetTheme: 'paper-3',
    patternTheme: 'poimandres',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'slack',
    name: 'Slack Theme',
    description: 'Professional look matching Slack\'s UI with clean design and balanced colors for team collaboration',
    pianoTheme: 'slack',
    backgroundTheme: 'slack',
    musicSheetTheme: 'paper-3',
    patternTheme: 'slack',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'brackets-light-pro',
    name: 'Brackets Light Pro',
    description: 'Clean, minimal theme inspired by Brackets editor with professional styling and light aesthetics',
    pianoTheme: 'bracketsLightPro',
    backgroundTheme: 'brackets-light-pro',
    musicSheetTheme: 'paper-2',
    patternTheme: 'brackets-light-pro',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'min-dark',
    name: 'Min Dark',
    description: 'Ultra-minimal dark theme with subtle grays for focused, distraction-free piano playing',
    pianoTheme: 'minDark',
    backgroundTheme: 'min-dark',
    musicSheetTheme: 'paper-3',
    patternTheme: 'min-dark',
    patternIntensity: 0.2,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'min-light',
    name: 'Min Light',
    description: 'Ultra-minimal light theme with subtle grays for clean, bright piano sessions',
    pianoTheme: 'minLight',
    backgroundTheme: 'min-light',
    musicSheetTheme: 'paper-2',
    patternTheme: 'min-light',
    patternIntensity: 0.15,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'zenburn',
    name: 'Zenburn',
    description: 'Low-contrast theme designed for reduced eye strain with warm, comfortable colors',
    pianoTheme: 'zenburn',
    backgroundTheme: 'zenburn',
    musicSheetTheme: 'paper-3',
    patternTheme: 'zenburn',
    patternIntensity: 0.25,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'base16',
    name: 'Base16',
    description: 'Comprehensive color scheme collection with balanced, accessible colors for inclusive design',
    pianoTheme: 'base16',
    backgroundTheme: 'base16',
    musicSheetTheme: 'paper-3',
    patternTheme: 'base16',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'tomorrow',
    name: 'Tomorrow',
    description: 'Balanced theme with clean design and comfortable color combinations for all-day use',
    pianoTheme: 'tomorrow',
    backgroundTheme: 'tomorrow',
    musicSheetTheme: 'paper-3',
    patternTheme: 'tomorrow',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    description: 'Retro color scheme inspired by old computers with warm, earthy tones and nostalgic feel',
    pianoTheme: 'gruvbox',
    backgroundTheme: 'gruvbox',
    musicSheetTheme: 'paper-3',
    patternTheme: 'gruvbox',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'iceberg',
    name: 'Iceberg',
    description: 'Cool blue theme with Japanese design influence and icy aesthetics for serene playing',
    pianoTheme: 'iceberg',
    backgroundTheme: 'iceberg',
    musicSheetTheme: 'paper-3',
    patternTheme: 'iceberg',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'forest-night',
    name: 'Forest Night',
    description: 'Nature-inspired dark theme with deep greens and earthy forest tones for peaceful sessions',
    pianoTheme: 'forestNight',
    backgroundTheme: 'forest-night',
    musicSheetTheme: 'paper-3',
    patternTheme: 'forest-night',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    description: 'Warm, comfortable color palette with soft pinks and gentle greens for cozy piano playing',
    pianoTheme: 'rosePine',
    backgroundTheme: 'rose-pine',
    musicSheetTheme: 'paper-3',
    patternTheme: 'rose-pine',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    description: 'Cozy pastel theme with warm colors and multiple flavor variants for a comforting experience',
    pianoTheme: 'catppuccin',
    backgroundTheme: 'catppuccin',
    musicSheetTheme: 'paper-3',
    patternTheme: 'catppuccin',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  {
    id: 'everforest',
    name: 'Everforest',
    description: 'Warm green color scheme with natural forest-inspired aesthetics for grounding piano sessions',
    pianoTheme: 'everforest',
    backgroundTheme: 'everforest',
    musicSheetTheme: 'paper-3',
    patternTheme: 'everforest',
    patternIntensity: 0.3,
    category: 'minimalist',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.minimalist,
    quoteStyle: QUOTE_STYLES.minimalist,
    playbackBarStyle: PLAYBACK_BAR_STYLES.minimalist,
  },
  
  // Luxurious Presets
  {
    id: 'gold-standard',
    name: 'Gold Standard',
    description: 'Opulent rose gold with leather luxury',
    pianoTheme: 'roseGold',
    backgroundTheme: 'gufeng-vermillion-gold',
    musicSheetTheme: 'paper-14',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'royal-court',
    name: 'Royal Court',
    description: 'Regal mahogany with imperial vermillion',
    pianoTheme: 'mahogany',
    backgroundTheme: 'gufeng-vermillion-gold',
    musicSheetTheme: 'paper-10',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'diamond-nights',
    name: 'Diamond Nights',
    description: 'Sophisticated black with divine radiance',
    pianoTheme: 'black',
    backgroundTheme: 'sacred-light-glory',
    musicSheetTheme: 'paper-12',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'emerald-palace',
    name: 'Emerald Palace',
    description: 'Majestic metal with emerald gold',
    pianoTheme: 'metal',
    backgroundTheme: 'islamic-emerald-gold',
    musicSheetTheme: 'paper-12',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'platinum-suite',
    name: 'Platinum Suite',
    description: 'Premium metal with marble refinement',
    pianoTheme: 'metal',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-12',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'velvet-lounge',
    name: 'Velvet Lounge',
    description: 'Plush mahogany with peacock divine',
    pianoTheme: 'mahogany',
    backgroundTheme: 'leela-peacock-divine',
    musicSheetTheme: 'paper-14',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  {
    id: 'crystal-ballroom',
    name: 'Crystal Ballroom',
    description: 'Sparkling white with sacred glory',
    pianoTheme: 'white',
    backgroundTheme: 'sacred-light-glory',
    musicSheetTheme: 'paper-2',
    category: 'luxurious',
    headerStyle: 'luxurious-light',
    headerThemeStyle: HEADER_THEME_STYLES.luxurious,
    quoteStyle: QUOTE_STYLES.luxurious,
    playbackBarStyle: PLAYBACK_BAR_STYLES.luxurious,
  },
  
  // Additional Classic Presets
  {
    id: 'classical-concert',
    name: 'Classical Concert',
    description: 'Traditional concert with vintage paper',
    pianoTheme: 'black',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-1',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  {
    id: 'beethoven-legacy',
    name: 'Beethoven Legacy',
    description: 'Historic mahogany with parchment scroll',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-10',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  {
    id: 'mozart-chamber',
    name: 'Mozart Chamber',
    description: 'Chamber music with aged elegance',
    pianoTheme: 'wooden',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-3',
    category: 'classic',
    headerStyle: 'classic-serif',
    headerThemeStyle: HEADER_THEME_STYLES.classic,
    quoteStyle: QUOTE_STYLES.classic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.classic,
  },
  
  // Sci-Fi Presets
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'High-tech, low-life aesthetic with neon-drenched cityscapes.',
    pianoTheme: 'metal',
    backgroundTheme: 'cyberpunk-neon',
    musicSheetTheme: 'paper-12',
    patternTheme: 'glitch-grid',
    category: 'sci-fi',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern, // Or a new sci-fi style
    quoteStyle: QUOTE_STYLES.modern, // Or a new sci-fi style
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern, // Or a new sci-fi style
  },

  // Additional Modern Presets
  {
    id: 'contemporary-studio',
    name: 'Contemporary Studio',
    description: 'Modern studio with sleek design',
    pianoTheme: 'metal',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-2',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  {
    id: 'urban-loft',
    name: 'Urban Loft',
    description: 'Industrial loft with recycled paper',
    pianoTheme: 'metal',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-7',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  {
    id: 'scandinavian-design',
    name: 'Scandinavian Design',
    description: 'Nordic minimalism with clean lines',
    pianoTheme: 'nordicIce',
    backgroundTheme: 'light-gray',
    musicSheetTheme: 'paper-2',
    category: 'modern',
    headerStyle: 'modern-sans',
    headerThemeStyle: HEADER_THEME_STYLES.modern,
    quoteStyle: QUOTE_STYLES.modern,
    playbackBarStyle: PLAYBACK_BAR_STYLES.modern,
  },
  
  // Additional Cultural Presets
  {
    id: 'tea-ceremony',
    name: 'Tea Ceremony',
    description: 'Japanese tea house with tatami mats and bamboo shadows',
    pianoTheme: 'wooden',
    backgroundTheme: 'zen-bamboo-stone',
    musicSheetTheme: 'paper-7',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'temple-bells',
    name: 'Temple Bells',
    description: 'Sacred temple with saffron marigold',
    pianoTheme: 'wooden',
    backgroundTheme: 'leela-saffron-marigold',
    musicSheetTheme: 'paper-10',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'silk-road',
    name: 'Silk Road',
    description: 'Ancient trade route with scroll wisdom',
    pianoTheme: 'mahogany',
    backgroundTheme: 'isha-earth-mystic',
    musicSheetTheme: 'paper-10',
    category: 'cultural',
    headerStyle: 'cultural-serif',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'crystal-consciousness',
    name: 'Crystal Consciousness',
    description: 'New Age sacred geometry with crystalline energy fields',
    pianoTheme: 'white',
    backgroundTheme: 'sacred-light-glory',
    musicSheetTheme: 'paper-13',
    patternTheme: 'crystal-energy',
    category: 'cultural',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  {
    id: 'cosmic-meditation',
    name: 'Cosmic Meditation',
    description: 'Universal consciousness with celestial mandala patterns, New Age',
    pianoTheme: 'nordicIce',
    backgroundTheme: 'morning-sky',
    musicSheetTheme: 'paper-8',
    patternTheme: 'cosmic-mandala',
    category: 'cultural',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.cultural,
    quoteStyle: QUOTE_STYLES.cultural,
    playbackBarStyle: PLAYBACK_BAR_STYLES.cultural,
  },
  
  // Additional Nature Presets
  {
    id: 'mountain-mist',
    name: 'Mountain Mist',
    description: 'Misty mountains with bamboo stone',
    pianoTheme: 'wooden',
    backgroundTheme: 'zen-bamboo-stone',
    musicSheetTheme: 'paper-6',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  {
    id: 'rainforest',
    name: 'Rainforest',
    description: 'Lush rainforest with recycled eco paper',
    pianoTheme: 'wooden',
    backgroundTheme: 'gradient-forest',
    musicSheetTheme: 'paper-7',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  {
    id: 'desert-dunes',
    name: 'Desert Dunes',
    description: 'Sandy dunes with kraft texture',
    pianoTheme: 'wooden',
    backgroundTheme: 'isha-earth-mystic',
    musicSheetTheme: 'paper-11',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  {
    id: 'autumn-leaves',
    name: 'Autumn Leaves',
    description: 'Fall colors with canvas warmth',
    pianoTheme: 'mahogany',
    backgroundTheme: 'warm',
    musicSheetTheme: 'paper-15',
    category: 'nature',
    headerStyle: 'nature-serif',
    headerThemeStyle: HEADER_THEME_STYLES.nature,
    quoteStyle: QUOTE_STYLES.nature,
    playbackBarStyle: PLAYBACK_BAR_STYLES.nature,
  },
  
  // Additional Artistic Presets
  {
    id: 'impressionist',
    name: 'Impressionist',
    description: 'Monet-inspired with watercolor paper',
    pianoTheme: 'white',
    backgroundTheme: 'gradient-sunset',
    musicSheetTheme: 'paper-8',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
  {
    id: 'abstract-expression',
    name: 'Abstract Expression',
    description: 'Bold colors with canvas texture',
    pianoTheme: 'roseGold',
    backgroundTheme: 'gradient-ocean',
    musicSheetTheme: 'paper-15',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    description: 'Geometric elegance with marble sophistication',
    pianoTheme: 'black',
    backgroundTheme: 'cool',
    musicSheetTheme: 'paper-12',
    category: 'artistic',
    headerStyle: 'artistic-italic',
    headerThemeStyle: HEADER_THEME_STYLES.artistic,
    quoteStyle: QUOTE_STYLES.artistic,
    playbackBarStyle: PLAYBACK_BAR_STYLES.artistic,
  },
];

/**
 * Get preset by ID
 */
export function getPresetById(presetId: string): ThemePreset | undefined {
  return THEME_PRESETS.find(preset => preset.id === presetId);
}

/**
 * Get presets by category
 */
export function getPresetsByCategory(category: ThemePresetCategory): ThemePreset[] {
  return THEME_PRESETS.filter(preset => preset.category === category);
}

/**
 * Get all preset categories with metadata
 */
export function getPresetCategories(): Array<{ id: ThemePresetCategory; name: string; description: string }> {
  return [
    { id: 'classic', name: 'Classic', description: 'Timeless traditional combinations' },
    { id: 'modern', name: 'Modern', description: 'Contemporary minimalist styles' },
    { id: 'vintage', name: 'Vintage', description: 'Old-world charm and nostalgia' },
    { id: 'professional', name: 'Professional', description: 'Concert halls and studios' },
    { id: 'romantic', name: 'Romantic', description: 'Soft, dreamy, and intimate' },
    { id: 'energetic', name: 'Energetic', description: 'Vibrant and lively combinations' },
    { id: 'minimalist', name: 'Minimalist', description: 'Clean and simple aesthetics' },
    { id: 'luxurious', name: 'Luxurious', description: 'Premium and opulent styles' },
    { id: 'cultural', name: 'Cultural', description: 'Traditional and spiritual themes' },
    { id: 'nature', name: 'Nature', description: 'Natural and organic themes' },
    { id: 'artistic', name: 'Artistic', description: 'Creative and expressive combinations' },
  ];
}

/**
 * Get random preset from a category
 */
export function getRandomPreset(category?: ThemePresetCategory): ThemePreset {
  const presets = category ? getPresetsByCategory(category) : THEME_PRESETS;
  return presets[Math.floor(Math.random() * presets.length)];
}

/**
 * Get all presets count by category
 */
export function getPresetCounts(): Record<ThemePresetCategory, number> {
  return THEME_PRESETS.reduce((acc, preset) => {
    acc[preset.category] = (acc[preset.category] || 0) + 1;
    return acc;
  }, {} as Record<ThemePresetCategory, number>);
}
